server:
  port: 8081
  servlet:
    context-path: /socialite
spring:
  application:
    name: Socialite
  config:
    import: optional:file:env.properties
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}